version: '3'

services:
  testimgbackend:
    image: a72f0377e78f
    container_name: testimgbackend
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "9880:5423"
